name: TfNSW Service Alerts Archiver
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 1
        path: runenv
    - uses: actions/checkout@v2
      with:
        ref: data
        fetch-depth: 1
        path: data
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: cd runenv && yarn
    - name: Run script
      run: cd runenv && node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TFNSW_API_KEY: ${{ secrets.TFNSW_API_KEY }}
